name: Publish gem to rubygems.org

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  push:
    if: github.repository == 'ruby/psych'
    runs-on: ubuntu-latest

    environment:
      name: rubygems.org
      url: https://rubygems.org/gems/psych

    permissions:
      contents: write
      id-token: write

    strategy:
      matrix:
        ruby: ["3.3", "jruby"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set up Ruby
        uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1.190.0
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

        # https://github.com/rubygems/rubygems/issues/5882
      - run: gem update --system
        if: matrix.ruby == 'jruby'

      - name: Publish to RubyGems
        uses: rubygems/release-gem@612653d273a73bdae1df8453e090060bb4db5f31 # v1

      - name: Create GitHub release
        run: |
          tag_name="$(git describe --tags --abbrev=0)"
          gh release create "${tag_name}" --verify-tag --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.MATZBOT_GITHUB_WORKFLOW_TOKEN }}
        if: matrix.ruby != 'jruby'
